version: '3.7'
services:

  postgres_cidenet:
    image: postgres:12
    container_name: postgres_cidenet
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cidenet-db
    ports:
      - "5432:5432"
    volumes:
      - ./data_base_init.sql:/docker-entrypoint-initdb.d/data_base_init.sql

  app:
    container_name: cidenet-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    restart: on-failure
    image: cidenet-api
    links:
      - postgres_cidenet
    depends_on:
      - postgres_cidenet
    environment:
      - "PORT=8888"
      - "API_PORT=8888"
      - "DB_HOST=postgres_cidenet"
      - "DB_DRIVER=postgres"
      - "DB_PASSWORD=admin"
      - "DB_NAME=cidenet-db"
      - "DB_PORT=5432"
      - "DB_USER=postgres"
      - "SCRIPTS_PATH=file:///migrations"
      - "MAX_SIZE=8192000"
      - "STORE=/cidenet-api"
